### ISSUE TITLE
Does not work on Debian wheezy linux

### ISSUE THREAD

**Issue by iTech-Developer** [waigo/waigo#26]
The [Shebang](https://en.wikipedia.org/wiki/Shebang_%28Unix%29) argument does not work on linux (i.e. *--harmony*)

    #!/usr/bin/env node --harmony

And it leads to the following error, because it consider the entire string **node --harmony** as the file name, it will work on Mac

    /usr/bin/env: node --harmony: No such file or directory

The workaround I am using is to replace it with the node path directly e.g. `#!/usr/local/bin/node --harmony`

**Comment by hiddentao** [comment]
This is redundant in v2.
