### ISSUE TITLE
single-page-app (SPA) support?

### ISSUE THREAD

**Issue by stela5** [waigo/waigo#29]
Can you use Waigo as the base architecture for a mobile cordova spa app?

http://waigojs.com/guide.html#views-and-output-formats mentions "single-page web versions and/or mobile apps".  Perhaps include a ToDo or other simple example?

**Comment by hiddentao** [comment]
Yep I've used Waigo with a phonegap/cordova app before just fine. You can just call each route with `?format=json` to get back JSON data.
