### ISSUE TITLE
Status

### ISSUE THREAD

**Issue by niallobrien** [waigo/waigo#40]
Hi all, is this project still in active development? Thanks in advance.

**Comment by hiddentao** [comment]
Absolutely. The `master` branch is under active development. Actually everything works, but tests need to be updated. Plus, the documentation site needs to be re-done.

On another note, I'm thinking of perhaps dropping Mongo in favour of RethinkDB, to enable people to build more reactive apps.

**Comment by hiddentao** [comment]
v2 is available for use, documentation is in progress (to be mostly finished within the next week). site updated - https://waigojs.com

**Comment by niallobrien** [comment]
Awesome stuff, I look forward to giving it a go. :) Keep up the great work!
