### ISSUE TITLE
CLI broken

### ISSUE THREAD

**Issue by gregbenner** [waigo/waigo#46]
`🌚  waigo: waigo init
[waigo-cli] npm install --save waigo@next semver
npm ERR! Darwin 15.5.0
npm ERR! argv "/Users/gnb/.nvm/versions/node/v6.0.0/bin/node" "/Users/gnb/.nvm/versions/node/v6.0.0/bin/npm" "install" "--save" "waigo@next" "semver"
npm ERR! node v6.0.0
npm ERR! npm  v3.8.6

npm ERR! No compatible version found: waigo@next
npm ERR! Valid install targets:
npm ERR! 2.1.3, 2.1.2, 2.1.1, 2.1.0, 2.1.0-beta6, 2.1.0-beta5, 2.1.0-beta4, 2.1.0-beta3, 2.1.0-beta2, 2.1.0-beta1, 2.1.0-alpha1, 2.0.0, 1.7.10, 1.7.9, 1.7.8, 1.7.7, 1.7.6, 1.7.5, 1.7.4, 1.7.3, 1.7.2, 1.7.1, 1.7.0, 1.6.1, 1.6.0, 1.5.7, 1.5.6, 1.5.5, 1.5.4, 1.5.3, 1.5.2, 1.5.1, 1.5.0, 1.4.1, 1.4.0, 1.3.5, 1.3.4, 1.3.3, 1.3.2, 1.3.1, 1.3.0, 1.2.3, 1.2.2, 1.2.1, 1.2.0, 1.1.2, 1.1.1, 1.1.0, 1.0.0, 0.6.8, 0.6.7, 0.6.6, 0.6.5, 0.6.4, 0.6.3, 0.6.2, 0.6.1, 0.6.0, 0.5.1, 0.5.0, 0.4.5, 0.4.4, 0.4.3, 0.4.2, 0.4.0, 0.3.0, 0.2.1, 0.2.0, 0.1.0
npm ERR!
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     https://github.com/npm/npm/issues

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/gnb/Desktop/CURRENT_SITES/waigo/npm-debug.log
Error: 1
    at maybeWrapAsError (/Users/gnb/.nvm/versions/node/v6.0.0/lib/node_modules/waigo/node_modules/bluebird/js/release/util.js:61:12)
    at /Users/gnb/.nvm/versions/node/v6.0.0/lib/node_modules/waigo/node_modules/bluebird/js/release/nodeback.js:38:50
    at /Users/gnb/.nvm/versions/node/v6.0.0/lib/node_modules/waigo/node_modules/shelljs/src/exec.js:178:7
    at ChildProcess.exithandler (child_process.js:209:5)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:850:16)
    at Socket.<anonymous> (internal/child_process.js:323:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose](net.js:485:12)`

**Comment by hiddentao** [comment]
Thanks, should be fixed in 2.1.4.
